/* Auto-generated by generate-handlers — DO NOT EDIT */
import 'dart:typed_data';

import 'package:blerpc_central/proto/blerpc.pb.dart';

/// Auto-generated RPC method wrappers for blerpc commands.
mixin GeneratedClientMixin {
  Future<Uint8List> call(String cmdName, Uint8List requestData);
  Future<List<Uint8List>> streamReceive(String cmdName, Uint8List requestData);
  Future<Uint8List> streamSend(
      String cmdName, List<Uint8List> messages, String finalCmdName);

  Future<EchoResponse> echo({String message = ''}) async {
    final req = EchoRequest()..message = message;
    final respData =
        await call('echo', Uint8List.fromList(req.writeToBuffer()));
    return EchoResponse.fromBuffer(respData);
  }

  Future<FlashReadResponse> flashRead({int address = 0, int length = 0}) async {
    final req = FlashReadRequest()
      ..address = address
      ..length = length;
    final respData =
        await call('flash_read', Uint8List.fromList(req.writeToBuffer()));
    return FlashReadResponse.fromBuffer(respData);
  }

  Future<DataWriteResponse> dataWrite({List<int> data = const <int>[]}) async {
    final req = DataWriteRequest()..data = data;
    final respData =
        await call('data_write', Uint8List.fromList(req.writeToBuffer()));
    return DataWriteResponse.fromBuffer(respData);
  }

  Future<List<CounterStreamResponse>> counterStream({int count = 0}) async {
    final req = CounterStreamRequest()..count = count;
    final responses = await streamReceive(
        'counter_stream', Uint8List.fromList(req.writeToBuffer()));
    return responses.map((data) => CounterStreamResponse.fromBuffer(data)).toList();
  }

  Future<CounterUploadResponse> counterUpload(List<CounterUploadRequest> messages) async {
    final raw =
        messages.map((m) => Uint8List.fromList(m.writeToBuffer())).toList();
    final respData = await streamSend('counter_upload', raw, 'counter_upload');
    return CounterUploadResponse.fromBuffer(respData);
  }
}
