/* Auto-generated by generate-handlers — DO NOT EDIT */
import Foundation
import SwiftProtobuf

/// Auto-generated RPC method protocol.
/// Conform to this protocol and implement call/streamReceive/streamSend.
protocol GeneratedClientProtocol {
    func call(cmdName: String, requestData: Data) async throws -> Data
    func streamReceive(cmdName: String, requestData: Data) async throws -> [Data]
    func streamSend(cmdName: String, messages: [Data], finalCmdName: String) async throws -> Data
}

extension GeneratedClientProtocol {
    func echo(message: String = "") async throws -> Blerpc_EchoResponse {
        var req = Blerpc_EchoRequest()
        req.message = message
        let respData = try await call(cmdName: "echo", requestData: try req.serializedData())
        return try Blerpc_EchoResponse(serializedBytes: respData)
    }

    func flashRead(address: UInt32 = 0, length: UInt32 = 0) async throws -> Blerpc_FlashReadResponse {
        var req = Blerpc_FlashReadRequest()
        req.address = address
        req.length = length
        let respData = try await call(cmdName: "flash_read", requestData: try req.serializedData())
        return try Blerpc_FlashReadResponse(serializedBytes: respData)
    }

    func dataWrite(data: Data = Data()) async throws -> Blerpc_DataWriteResponse {
        var req = Blerpc_DataWriteRequest()
        req.data = data
        let respData = try await call(cmdName: "data_write", requestData: try req.serializedData())
        return try Blerpc_DataWriteResponse(serializedBytes: respData)
    }

    func counterStream(count: UInt32 = 0) async throws -> [Blerpc_CounterStreamResponse] {
        var req = Blerpc_CounterStreamRequest()
        req.count = count
        let responses = try await streamReceive(cmdName: "counter_stream", requestData: try req.serializedData())
        return try responses.map { try Blerpc_CounterStreamResponse(serializedBytes: $0) }
    }

    func counterUpload(messages: [Blerpc_CounterUploadRequest]) async throws -> Blerpc_CounterUploadResponse {
        let raw = try messages.map { try $0.serializedData() }
        let respData = try await streamSend(cmdName: "counter_upload", messages: raw, finalCmdName: "counter_upload")
        return try Blerpc_CounterUploadResponse(serializedBytes: respData)
    }
}
