package main

import (
	"fmt"
	"strings"
)

func generateSwiftClient(commands []Command, streaming map[string]string, pkg string) string {
	pkgCap := strings.ToUpper(pkg[:1]) + pkg[1:]
	var b strings.Builder

	b.WriteString("/* Auto-generated by generate-handlers — DO NOT EDIT */\n")
	b.WriteString("import Foundation\n")
	b.WriteString("import SwiftProtobuf\n")
	b.WriteByte('\n')
	b.WriteString("/// Auto-generated RPC method protocol.\n")
	b.WriteString("/// Conform to this protocol and implement call/streamReceive/streamSend.\n")
	b.WriteString("protocol GeneratedClientProtocol {\n")
	b.WriteString("    func call(cmdName: String, requestData: Data) async throws -> Data\n")
	b.WriteString("    func streamReceive(cmdName: String, requestData: Data) async throws -> [Data]\n")
	b.WriteString("    func streamSend(cmdName: String, messages: [Data], finalCmdName: String) async throws -> Data\n")
	b.WriteString("}\n")
	b.WriteByte('\n')
	b.WriteString("extension GeneratedClientProtocol {\n")

	first := true
	for _, cmd := range commands {
		if _, ok := streaming[cmd.Snake]; ok {
			continue
		}

		reqCls := pkgCap + "_" + cmd.RequestMsg
		respCls := pkgCap + "_" + cmd.ResponseMsg
		methodName := toLowerCamel(cmd.Camel)

		// Build parameters
		var params []string
		for _, f := range cmd.RequestFields {
			swType := resolveSwiftType(f)
			def := resolveSwiftDefault(f)
			propName := swiftPropertyName(f.Name)
			params = append(params, fmt.Sprintf("%s: %s = %s", propName, swType, def))
		}

		paramsStr := strings.Join(params, ", ")

		if !first {
			b.WriteByte('\n')
		}
		first = false

		b.WriteString(fmt.Sprintf("    func %s(%s) async throws -> %s {\n", methodName, paramsStr, respCls))
		b.WriteString(fmt.Sprintf("        var req = %s()\n", reqCls))
		for _, f := range cmd.RequestFields {
			propName := swiftPropertyName(f.Name)
			b.WriteString(fmt.Sprintf("        req.%s = %s\n", propName, propName))
		}
		b.WriteString(fmt.Sprintf("        let respData = try await call(cmdName: \"%s\", requestData: try req.serializedData())\n", cmd.Snake))
		b.WriteString(fmt.Sprintf("        return try %s(serializedBytes: respData)\n", respCls))
		b.WriteString("    }\n")
	}

	// Streaming methods
	for _, cmd := range commands {
		dir, ok := streaming[cmd.Snake]
		if !ok {
			continue
		}

		reqCls := pkgCap + "_" + cmd.RequestMsg
		respCls := pkgCap + "_" + cmd.ResponseMsg
		methodName := toLowerCamel(cmd.Camel)

		b.WriteByte('\n')

		if dir == "p2c" {
			var params []string
			for _, f := range cmd.RequestFields {
				swType, ok := swiftTypes[f.Type]
				if !ok {
					swType = "Any"
				}
				def, ok := swiftDefaults[f.Type]
				if !ok {
					def = "nil"
				}
				propName := swiftPropertyName(f.Name)
				params = append(params, fmt.Sprintf("%s: %s = %s", propName, swType, def))
			}
			paramsStr := strings.Join(params, ", ")

			b.WriteString(fmt.Sprintf("    func %s(%s) async throws -> [%s] {\n", methodName, paramsStr, respCls))
			b.WriteString(fmt.Sprintf("        var req = %s()\n", reqCls))
			for _, f := range cmd.RequestFields {
				propName := swiftPropertyName(f.Name)
				b.WriteString(fmt.Sprintf("        req.%s = %s\n", propName, propName))
			}
			b.WriteString(fmt.Sprintf("        let responses = try await streamReceive(cmdName: \"%s\", requestData: try req.serializedData())\n", cmd.Snake))
			b.WriteString(fmt.Sprintf("        return try responses.map { try %s(serializedBytes: $0) }\n", respCls))
			b.WriteString("    }\n")
		} else {
			b.WriteString(fmt.Sprintf("    func %s(messages: [%s]) async throws -> %s {\n", methodName, reqCls, respCls))
			b.WriteString("        let raw = try messages.map { try $0.serializedData() }\n")
			b.WriteString(fmt.Sprintf("        let respData = try await streamSend(cmdName: \"%s\", messages: raw, finalCmdName: \"%s\")\n", cmd.Snake, cmd.Snake))
			b.WriteString(fmt.Sprintf("        return try %s(serializedBytes: respData)\n", respCls))
			b.WriteString("    }\n")
		}
	}

	b.WriteString("}\n")

	return b.String()
}
