package main

import (
	"fmt"
	"strings"
)

func generateCClientHeader(commands []Command, streaming map[string]string, callbacks map[string]bool, pkg string) string {
	var b strings.Builder

	guard := strings.ToUpper(pkg) + "_GENERATED_CLIENT_H"
	lines := []string{
		"/* Auto-generated by generate-handlers — DO NOT EDIT */",
		"#ifndef " + guard,
		"#define " + guard,
		"",
		`#include "` + pkg + `.pb.h"`,
		"#include <pb_encode.h>",
		"#include <pb_decode.h>",
		"#include <stdint.h>",
		"#include <stddef.h>",
		"#include <stdbool.h>",
		"#include <string.h>",
		"",
		"#ifdef __cplusplus",
		`extern "C" {`,
		"#endif",
		"",
		"/* Callback for P2C streaming response payloads */",
		"typedef int (*" + pkg + "_on_stream_resp_t)(const uint8_t *data, size_t len, void *ctx);",
		"",
		"/* Callback for C2P streaming message serialization */",
		"typedef int (*" + pkg + "_next_msg_t)(size_t index, uint8_t *buf, size_t buf_size,",
		"                                 size_t *len, void *ctx);",
		"",
		"/* User-provided RPC transport functions */",
		"extern int " + pkg + "_rpc_call(const char *cmd_name,",
		"                           const uint8_t *req_data, size_t req_len,",
		"                           uint8_t *resp_data, size_t resp_size, size_t *resp_len);",
		"",
		"extern int " + pkg + "_stream_receive(const char *cmd_name,",
		"                                 const uint8_t *req_data, size_t req_len,",
		"                                 " + pkg + "_on_stream_resp_t on_resp, void *ctx);",
		"",
		"extern int " + pkg + "_stream_send(const char *cmd_name, size_t msg_count,",
		"                              " + pkg + "_next_msg_t next_msg, void *msg_ctx,",
		"                              const char *final_cmd_name,",
		"                              uint8_t *resp_data, size_t resp_size, size_t *resp_len);",
		"",
		"/* Generated typed RPC functions */",
	}
	for _, l := range lines {
		b.WriteString(l)
		b.WriteByte('\n')
	}

	for _, cmd := range commands {
		params := cClientParams(cmd, streaming, callbacks, pkg)
		b.WriteString(fmt.Sprintf("int %s_%s(%s);\n", pkg, cmd.Snake, strings.Join(params, ", ")))
	}

	tail := []string{
		"",
		"#ifdef __cplusplus",
		"}",
		"#endif",
		"",
		"#endif /* " + guard + " */",
	}
	for _, l := range tail {
		b.WriteString(l)
		b.WriteByte('\n')
	}

	return b.String()
}

func generateCClientSource(commands []Command, streaming map[string]string, callbacks map[string]bool, pkg string) string {
	var b strings.Builder

	b.WriteString("/* Auto-generated by generate-handlers — DO NOT EDIT */\n")
	b.WriteString("#include \"generated_client.h\"\n\n")

	// Check if we need helpers
	needDecode := false
	needEncode := false
	needRespBuf := false
	for _, cmd := range commands {
		if _, ok := streaming[cmd.Snake]; ok {
			continue
		}
		for _, f := range cmd.ResponseFields {
			if callbacks[cmd.ResponseMsg+"."+f.Name] {
				needDecode = true
				needRespBuf = true
			}
		}
		for _, f := range cmd.RequestFields {
			if callbacks[cmd.RequestMsg+"."+f.Name] {
				needEncode = true
			}
		}
	}

	up := strings.ToUpper(pkg)
	bufMacro := up + "_GENERATED_RESP_BUF_SIZE"

	// Internal response buffer for FT_CALLBACK response commands
	if needRespBuf {
		b.WriteString("#ifndef " + bufMacro + "\n")
		b.WriteString("#define " + bufMacro + " 4096\n")
		b.WriteString("#endif\n")
		b.WriteString("static uint8_t _" + pkg + "_resp_buf[" + bufMacro + "];\n\n")
	}

	if needDecode {
		b.WriteString("/* Decode context for FT_CALLBACK bytes fields */\n")
		b.WriteString("struct _" + pkg + "_bytes_decode_ctx {\n")
		b.WriteString("    uint8_t *buf;\n")
		b.WriteString("    size_t buf_size;\n")
		b.WriteString("    size_t decoded_len;\n")
		b.WriteString("};\n\n")
		b.WriteString("static bool _" + pkg + "_decode_bytes_cb(pb_istream_t *stream,\n")
		b.WriteString("                                     const pb_field_t *field, void **arg)\n")
		b.WriteString("{\n")
		b.WriteString("    (void)field;\n")
		b.WriteString("    struct _" + pkg + "_bytes_decode_ctx *ctx =\n")
		b.WriteString("        (struct _" + pkg + "_bytes_decode_ctx *)*arg;\n")
		b.WriteString("    size_t len = stream->bytes_left;\n")
		b.WriteString("    if (len > ctx->buf_size - ctx->decoded_len) return false;\n")
		b.WriteString("    if (!pb_read(stream, ctx->buf + ctx->decoded_len, len)) return false;\n")
		b.WriteString("    ctx->decoded_len += len;\n")
		b.WriteString("    return true;\n")
		b.WriteString("}\n\n")
	}

	if needEncode {
		b.WriteString("/* Encode context for FT_CALLBACK bytes fields */\n")
		b.WriteString("struct _" + pkg + "_bytes_encode_ctx {\n")
		b.WriteString("    const uint8_t *data;\n")
		b.WriteString("    size_t data_len;\n")
		b.WriteString("};\n\n")
		b.WriteString("static bool _" + pkg + "_encode_bytes_cb(pb_ostream_t *stream,\n")
		b.WriteString("                                     const pb_field_t *field,\n")
		b.WriteString("                                     void *const *arg)\n")
		b.WriteString("{\n")
		b.WriteString("    const struct _" + pkg + "_bytes_encode_ctx *ctx =\n")
		b.WriteString("        *(const struct _" + pkg + "_bytes_encode_ctx **)arg;\n")
		b.WriteString("    if (!pb_encode_tag_for_field(stream, field)) return false;\n")
		b.WriteString("    if (!pb_encode_varint(stream, ctx->data_len)) return false;\n")
		b.WriteString("    return pb_write(stream, ctx->data, ctx->data_len);\n")
		b.WriteString("}\n\n")
	}

	// Per-command generation
	for _, cmd := range commands {
		dir, isStreaming := streaming[cmd.Snake]
		reqMsg := pkg + "_" + cmd.RequestMsg
		respMsg := pkg + "_" + cmd.ResponseMsg
		params := cClientParams(cmd, streaming, callbacks, pkg)

		if isStreaming && dir == "p2c" {
			// P2C streaming: callback struct + on_resp function + main function
			b.WriteString(fmt.Sprintf("struct _"+pkg+"_%s_ctx {\n", cmd.Snake))
			b.WriteString(fmt.Sprintf("    %s *results;\n", respMsg))
			b.WriteString("    size_t max_results;\n")
			b.WriteString("    size_t count;\n")
			b.WriteString("};\n\n")

			b.WriteString(fmt.Sprintf("static int _"+pkg+"_%s_on_resp(const uint8_t *data, size_t len,\n", cmd.Snake))
			b.WriteString(fmt.Sprintf("                              %svoid *ctx)\n", strings.Repeat(" ", len(cmd.Snake))))
			b.WriteString("{\n")
			b.WriteString(fmt.Sprintf("    struct _"+pkg+"_%s_ctx *c = (struct _"+pkg+"_%s_ctx *)ctx;\n", cmd.Snake, cmd.Snake))
			b.WriteString("    if (c->count >= c->max_results) return -1;\n")
			b.WriteString(fmt.Sprintf("    c->results[c->count] = (%s)%s_init_zero;\n", respMsg, respMsg))
			b.WriteString("    pb_istream_t istream = pb_istream_from_buffer(data, len);\n")
			b.WriteString(fmt.Sprintf("    if (!pb_decode(&istream, %s_fields, &c->results[c->count])) return -1;\n", respMsg))
			b.WriteString("    c->count++;\n")
			b.WriteString("    return 0;\n")
			b.WriteString("}\n\n")

			b.WriteString(fmt.Sprintf("int %s_%s(%s)\n", pkg, cmd.Snake, strings.Join(params, ", ")))
			b.WriteString("{\n")
			b.WriteString(fmt.Sprintf("    %s req = %s_init_zero;\n", reqMsg, reqMsg))
			for _, f := range cmd.RequestFields {
				if f.Type == "string" {
					b.WriteString(fmt.Sprintf("    strncpy(req.%s, %s, sizeof(req.%s) - 1);\n", f.Name, f.Name, f.Name))
				} else {
					b.WriteString(fmt.Sprintf("    req.%s = %s;\n", f.Name, f.Name))
				}
			}
			b.WriteByte('\n')
			b.WriteString(fmt.Sprintf("    uint8_t req_buf[%s_size];\n", reqMsg))
			b.WriteString("    pb_ostream_t ostream = pb_ostream_from_buffer(req_buf, sizeof(req_buf));\n")
			b.WriteString(fmt.Sprintf("    if (!pb_encode(&ostream, %s_fields, &req)) return -1;\n", reqMsg))
			b.WriteByte('\n')
			b.WriteString(fmt.Sprintf("    struct _"+pkg+"_%s_ctx ctx = {\n", cmd.Snake))
			b.WriteString("        .results = results, .max_results = max_results, .count = 0\n")
			b.WriteString("    };\n")
			b.WriteString(fmt.Sprintf("    if ("+pkg+"_stream_receive(\"%s\", req_buf, ostream.bytes_written,\n", cmd.Snake))
			b.WriteString(fmt.Sprintf("                              _"+pkg+"_%s_on_resp, &ctx) != 0) return -1;\n", cmd.Snake))
			b.WriteByte('\n')
			b.WriteString("    *result_count = ctx.count;\n")
			b.WriteString("    return 0;\n")
			b.WriteString("}\n\n")

		} else if isStreaming && dir == "c2p" {
			// C2P streaming: next_msg struct + callback + main function
			b.WriteString(fmt.Sprintf("struct _"+pkg+"_%s_ctx {\n", cmd.Snake))
			b.WriteString(fmt.Sprintf("    const %s *messages;\n", reqMsg))
			b.WriteString("};\n\n")

			b.WriteString(fmt.Sprintf("static int _"+pkg+"_%s_next(size_t index, uint8_t *buf,\n", cmd.Snake))
			b.WriteString(fmt.Sprintf("                           %ssize_t buf_size, size_t *len, void *ctx)\n", strings.Repeat(" ", len(cmd.Snake))))
			b.WriteString("{\n")
			b.WriteString(fmt.Sprintf("    struct _"+pkg+"_%s_ctx *c = (struct _"+pkg+"_%s_ctx *)ctx;\n", cmd.Snake, cmd.Snake))
			b.WriteString("    pb_ostream_t ostream = pb_ostream_from_buffer(buf, buf_size);\n")
			b.WriteString(fmt.Sprintf("    if (!pb_encode(&ostream, %s_fields, &c->messages[index])) return -1;\n", reqMsg))
			b.WriteString("    *len = ostream.bytes_written;\n")
			b.WriteString("    return 0;\n")
			b.WriteString("}\n\n")

			b.WriteString(fmt.Sprintf("int %s_%s(%s)\n", pkg, cmd.Snake, strings.Join(params, ", ")))
			b.WriteString("{\n")
			b.WriteString(fmt.Sprintf("    struct _"+pkg+"_%s_ctx ctx = { .messages = messages };\n", cmd.Snake))
			b.WriteByte('\n')
			b.WriteString(fmt.Sprintf("    uint8_t resp_buf[%s_size];\n", respMsg))
			b.WriteString("    size_t resp_len;\n")
			b.WriteString(fmt.Sprintf("    if ("+pkg+"_stream_send(\"%s\", msg_count,\n", cmd.Snake))
			b.WriteString(fmt.Sprintf("                           _"+pkg+"_%s_next, &ctx,\n", cmd.Snake))
			b.WriteString(fmt.Sprintf("                           \"%s\", resp_buf, sizeof(resp_buf),\n", cmd.Snake))
			b.WriteString("                           &resp_len) != 0) return -1;\n")
			b.WriteByte('\n')
			b.WriteString(fmt.Sprintf("    *resp = (%s)%s_init_zero;\n", respMsg, respMsg))
			b.WriteString("    pb_istream_t istream = pb_istream_from_buffer(resp_buf, resp_len);\n")
			b.WriteString(fmt.Sprintf("    if (!pb_decode(&istream, %s_fields, resp)) return -1;\n", respMsg))
			b.WriteByte('\n')
			b.WriteString("    return 0;\n")
			b.WriteString("}\n\n")

		} else {
			// Unary command
			hasCbReq := false
			hasCbResp := false
			for _, f := range cmd.RequestFields {
				if callbacks[cmd.RequestMsg+"."+f.Name] {
					hasCbReq = true
				}
			}
			for _, f := range cmd.ResponseFields {
				if callbacks[cmd.ResponseMsg+"."+f.Name] {
					hasCbResp = true
				}
			}

			b.WriteString(fmt.Sprintf("int %s_%s(%s)\n", pkg, cmd.Snake, strings.Join(params, ", ")))
			b.WriteString("{\n")

			// Encode context setup for FT_CALLBACK request fields
			if hasCbReq {
				for _, f := range cmd.RequestFields {
					if callbacks[cmd.RequestMsg+"."+f.Name] {
						b.WriteString(fmt.Sprintf("    struct _"+pkg+"_bytes_encode_ctx _%s_ctx = {\n", f.Name))
						b.WriteString(fmt.Sprintf("        .data = %s, .data_len = %s_len\n", f.Name, f.Name))
						b.WriteString("    };\n")
					}
				}
			}

			// Init request
			b.WriteString(fmt.Sprintf("    %s req = %s_init_zero;\n", reqMsg, reqMsg))

			// Set request fields
			for _, f := range cmd.RequestFields {
				key := cmd.RequestMsg + "." + f.Name
				if callbacks[key] {
					b.WriteString(fmt.Sprintf("    req.%s.funcs.encode = _"+pkg+"_encode_bytes_cb;\n", f.Name))
					b.WriteString(fmt.Sprintf("    req.%s.arg = &_%s_ctx;\n", f.Name, f.Name))
				} else if f.Type == "string" {
					b.WriteString(fmt.Sprintf("    strncpy(req.%s, %s, sizeof(req.%s) - 1);\n", f.Name, f.Name, f.Name))
				} else {
					b.WriteString(fmt.Sprintf("    req.%s = %s;\n", f.Name, f.Name))
				}
			}
			b.WriteByte('\n')

			// Encode request
			if hasCbReq {
				b.WriteString("    pb_ostream_t sizing = PB_OSTREAM_SIZING;\n")
				b.WriteString(fmt.Sprintf("    if (!pb_encode(&sizing, %s_fields, &req)) return -1;\n", reqMsg))
				b.WriteString("    if (sizing.bytes_written > work_buf_size) return -1;\n")
				b.WriteByte('\n')
				b.WriteString("    pb_ostream_t ostream = pb_ostream_from_buffer(work_buf, work_buf_size);\n")
				b.WriteString(fmt.Sprintf("    if (!pb_encode(&ostream, %s_fields, &req)) return -1;\n", reqMsg))
			} else {
				b.WriteString(fmt.Sprintf("    uint8_t req_buf[%s_size];\n", reqMsg))
				b.WriteString("    pb_ostream_t ostream = pb_ostream_from_buffer(req_buf, sizeof(req_buf));\n")
				b.WriteString(fmt.Sprintf("    if (!pb_encode(&ostream, %s_fields, &req)) return -1;\n", reqMsg))
			}
			b.WriteByte('\n')

			// RPC call
			reqBufName := "req_buf"
			if hasCbReq {
				reqBufName = "work_buf"
			}
			if hasCbResp {
				b.WriteString("    size_t resp_len;\n")
				b.WriteString(fmt.Sprintf("    if ("+pkg+"_rpc_call(\"%s\", %s, ostream.bytes_written,\n", cmd.Snake, reqBufName))
				b.WriteString("                        _" + pkg + "_resp_buf, sizeof(_" + pkg + "_resp_buf),\n")
				b.WriteString("                        &resp_len) != 0) return -1;\n")
			} else {
				b.WriteString(fmt.Sprintf("    uint8_t resp_buf[%s_size];\n", respMsg))
				b.WriteString("    size_t resp_len;\n")
				b.WriteString(fmt.Sprintf("    if ("+pkg+"_rpc_call(\"%s\", %s, ostream.bytes_written,\n", cmd.Snake, reqBufName))
				b.WriteString("                        resp_buf, sizeof(resp_buf), &resp_len) != 0) return -1;\n")
			}
			b.WriteByte('\n')

			// Decode context for FT_CALLBACK response fields
			if hasCbResp {
				for _, f := range cmd.ResponseFields {
					if callbacks[cmd.ResponseMsg+"."+f.Name] {
						b.WriteString(fmt.Sprintf("    struct _"+pkg+"_bytes_decode_ctx _%s_ctx = {\n", f.Name))
						b.WriteString(fmt.Sprintf("        .buf = %s_buf, .buf_size = %s_buf_size, .decoded_len = 0\n", f.Name, f.Name))
						b.WriteString("    };\n")
					}
				}
			}

			// Decode response
			b.WriteString(fmt.Sprintf("    *resp = (%s)%s_init_zero;\n", respMsg, respMsg))
			if hasCbResp {
				for _, f := range cmd.ResponseFields {
					if callbacks[cmd.ResponseMsg+"."+f.Name] {
						b.WriteString(fmt.Sprintf("    resp->%s.funcs.decode = _"+pkg+"_decode_bytes_cb;\n", f.Name))
						b.WriteString(fmt.Sprintf("    resp->%s.arg = &_%s_ctx;\n", f.Name, f.Name))
					}
				}
			}

			isBuf := "_" + pkg + "_resp_buf"
			if !hasCbResp {
				isBuf = "resp_buf"
			}
			b.WriteString(fmt.Sprintf("    pb_istream_t istream = pb_istream_from_buffer(%s, resp_len);\n", isBuf))
			b.WriteString(fmt.Sprintf("    if (!pb_decode(&istream, %s_fields, resp)) return -1;\n", respMsg))

			// Set output lengths for FT_CALLBACK response fields
			if hasCbResp {
				b.WriteByte('\n')
				for _, f := range cmd.ResponseFields {
					if callbacks[cmd.ResponseMsg+"."+f.Name] {
						b.WriteString(fmt.Sprintf("    *%s_len = _%s_ctx.decoded_len;\n", f.Name, f.Name))
					}
				}
			}

			b.WriteByte('\n')
			b.WriteString("    return 0;\n")
			b.WriteString("}\n\n")
		}
	}

	return b.String()
}
