package main

import (
	"fmt"
	"strings"
)

func generateCHeader(commands []Command, pkg string) string {
	guard := strings.ToUpper(pkg) + "_GENERATED_HANDLERS_H"
	var b strings.Builder
	lines := []string{
		"/* Auto-generated by generate-handlers — DO NOT EDIT */",
		"#ifndef " + guard,
		"#define " + guard,
		"",
		"#include <stdint.h>",
		"#include <stddef.h>",
		"#include <pb_encode.h>",
		"",
		"#ifdef __cplusplus",
		`extern "C" {`,
		"#endif",
		"",
		"typedef int (*command_handler_fn)(const uint8_t *req_data, size_t req_len,",
		"                                  pb_ostream_t *ostream);",
		"",
		"struct handler_entry {",
		"    const char *name;",
		"    uint8_t name_len;",
		"    command_handler_fn handler;",
		"};",
		"",
		"command_handler_fn handlers_lookup(const char *name, uint8_t name_len);",
		"",
	}
	for _, l := range lines {
		b.WriteString(l)
		b.WriteByte('\n')
	}

	for _, cmd := range commands {
		pad := strings.Repeat(" ", len(cmd.Snake))
		b.WriteString(fmt.Sprintf("int handle_%s(const uint8_t *req_data, size_t req_len,\n", cmd.Snake))
		b.WriteString(fmt.Sprintf("                %spb_ostream_t *ostream);\n", pad))
		b.WriteByte('\n')
	}

	tail := []string{
		"#ifdef __cplusplus",
		"}",
		"#endif",
		"",
		"#endif /* " + guard + " */",
	}
	for _, l := range tail {
		b.WriteString(l)
		b.WriteByte('\n')
	}
	return b.String()
}

func generateCSource(commands []Command, callbacks map[string]bool, pkg string) string {
	var b strings.Builder

	header := []string{
		"/* Auto-generated by generate-handlers — DO NOT EDIT */",
		`#include "generated_handlers.h"`,
		`#include "` + pkg + `.pb.h"`,
		"#include <pb_encode.h>",
		"#include <pb_decode.h>",
		"#include <string.h>",
		"",
		"/* Discard callback for FT_CALLBACK fields during decode */",
		"static bool discard_bytes_cb(pb_istream_t *stream, const pb_field_t *field,",
		"                             void **arg)",
		"{",
		"    (void)field;",
		"    (void)arg;",
		"    uint8_t buf[64];",
		"    size_t left = stream->bytes_left;",
		"    while (left > 0) {",
		"        size_t n = left < sizeof(buf) ? left : sizeof(buf);",
		"        if (!pb_read(stream, buf, n)) return false;",
		"        left -= n;",
		"    }",
		"    return true;",
		"}",
		"",
	}
	for _, l := range header {
		b.WriteString(l)
		b.WriteByte('\n')
	}

	// Weak handler stubs
	for _, cmd := range commands {
		reqMsg := pkg + "_" + cmd.RequestMsg
		respMsg := pkg + "_" + cmd.ResponseMsg
		pad := strings.Repeat(" ", len(cmd.Snake))

		b.WriteString("__attribute__((weak))\n")
		b.WriteString(fmt.Sprintf("int handle_%s(const uint8_t *req_data, size_t req_len,\n", cmd.Snake))
		b.WriteString(fmt.Sprintf("                %spb_ostream_t *ostream)\n", pad))
		b.WriteString("{\n")

		// Decode request
		b.WriteString(fmt.Sprintf("    %s req = %s_init_zero;\n", reqMsg, reqMsg))

		// Discard callbacks for FT_CALLBACK request fields
		for _, field := range cmd.RequestFields {
			key := cmd.RequestMsg + "." + field.Name
			if callbacks[key] {
				b.WriteString(fmt.Sprintf("    req.%s.funcs.decode = discard_bytes_cb;\n", field.Name))
			}
		}

		b.WriteString("    pb_istream_t stream = pb_istream_from_buffer(req_data, req_len);\n")
		b.WriteString(fmt.Sprintf("    if (!pb_decode(&stream, %s_fields, &req)) return -1;\n", reqMsg))
		b.WriteByte('\n')

		// Encode response
		b.WriteString(fmt.Sprintf("    %s resp = %s_init_zero;\n", respMsg, respMsg))
		b.WriteString(fmt.Sprintf("    if (!pb_encode(ostream, %s_fields, &resp)) return -1;\n", respMsg))
		b.WriteString("    return 0;\n")
		b.WriteString("}\n")
		b.WriteByte('\n')
	}

	// Handler table
	b.WriteString("static const struct handler_entry handler_table[] = {\n")
	for _, cmd := range commands {
		b.WriteString(fmt.Sprintf("    {\"%s\", %d, handle_%s},\n", cmd.Snake, len(cmd.Snake), cmd.Snake))
	}
	b.WriteString("};\n")
	b.WriteByte('\n')

	// Lookup function
	b.WriteString("command_handler_fn handlers_lookup(const char *name, uint8_t name_len)\n")
	b.WriteString("{\n")
	b.WriteString("    size_t i;\n")
	b.WriteString("    for (i = 0; i < sizeof(handler_table) / sizeof(handler_table[0]); i++) {\n")
	b.WriteString("        if (handler_table[i].name_len == name_len &&\n")
	b.WriteString("            memcmp(handler_table[i].name, name, name_len) == 0) {\n")
	b.WriteString("            return handler_table[i].handler;\n")
	b.WriteString("        }\n")
	b.WriteString("    }\n")
	b.WriteString("    return NULL;\n")
	b.WriteString("}\n")

	return b.String()
}
