package main

import (
	"fmt"
	"strings"
)

func generateKotlinClient(commands []Command, streaming map[string]string, pkg string) string {
	// Capitalize package name for Java outer class name
	pkgCap := strings.ToUpper(pkg[:1]) + pkg[1:]
	var b strings.Builder

	b.WriteString("/* Auto-generated by generate-handlers — DO NOT EDIT */\n")
	b.WriteString("package com." + pkg + ".android.client\n")
	b.WriteByte('\n')
	b.WriteString("import com.google.protobuf.ByteString\n")
	b.WriteByte('\n')
	b.WriteString("/**\n")
	b.WriteString(" * Auto-generated RPC methods.\n")
	b.WriteString(" * Subclass and override for custom behavior.\n")
	b.WriteString(" */\n")
	b.WriteString("abstract class GeneratedClient {\n")
	b.WriteString("    protected abstract suspend fun call(cmdName: String, requestData: ByteArray): ByteArray\n")
	b.WriteString("    protected abstract suspend fun streamReceive(cmdName: String, requestData: ByteArray): List<ByteArray>\n")
	b.WriteString("    protected abstract suspend fun streamSend(cmdName: String, messages: List<ByteArray>, finalCmdName: String): ByteArray\n")
	b.WriteByte('\n')

	first := true
	for _, cmd := range commands {
		if _, ok := streaming[cmd.Snake]; ok {
			continue
		}

		reqCls := pkg + "." + pkgCap + "." + cmd.RequestMsg
		respCls := pkg + "." + pkgCap + "." + cmd.ResponseMsg
		methodName := toLowerCamel(cmd.Camel)

		// Build parameters
		var params []string
		for _, f := range cmd.RequestFields {
			ktType := resolveKotlinType(f)
			def := resolveKotlinDefault(f)
			params = append(params, fmt.Sprintf("%s: %s = %s", f.Name, ktType, def))
		}

		paramsStr := strings.Join(params, ", ")

		if !first {
			b.WriteByte('\n')
		}
		first = false

		b.WriteString(fmt.Sprintf("    open suspend fun %s(%s): %s {\n", methodName, paramsStr, respCls))
		b.WriteString(fmt.Sprintf("        val req = %s.newBuilder()\n", reqCls))
		for _, f := range cmd.RequestFields {
			setter := kotlinSetterName(f.Name)
			b.WriteString(fmt.Sprintf("            .%s(%s)\n", setter, f.Name))
		}
		b.WriteString("            .build()\n")
		b.WriteString(fmt.Sprintf("        val respData = call(\"%s\", req.toByteArray())\n", cmd.Snake))
		b.WriteString(fmt.Sprintf("        return %s.parseFrom(respData)\n", respCls))
		b.WriteString("    }\n")
	}

	// Streaming methods
	for _, cmd := range commands {
		dir, ok := streaming[cmd.Snake]
		if !ok {
			continue
		}

		reqCls := pkg + "." + pkgCap + "." + cmd.RequestMsg
		respCls := pkg + "." + pkgCap + "." + cmd.ResponseMsg
		methodName := toLowerCamel(cmd.Camel)

		b.WriteByte('\n')

		if dir == "p2c" {
			var params []string
			for _, f := range cmd.RequestFields {
				ktType := resolveKotlinType(f)
				def := resolveKotlinDefault(f)
				params = append(params, fmt.Sprintf("%s: %s = %s", f.Name, ktType, def))
			}
			paramsStr := strings.Join(params, ", ")

			b.WriteString(fmt.Sprintf("    open suspend fun %s(%s): List<%s> {\n", methodName, paramsStr, respCls))
			b.WriteString(fmt.Sprintf("        val req = %s.newBuilder()\n", reqCls))
			for _, f := range cmd.RequestFields {
				setter := kotlinSetterName(f.Name)
				b.WriteString(fmt.Sprintf("            .%s(%s)\n", setter, f.Name))
			}
			b.WriteString("            .build()\n")
			b.WriteString(fmt.Sprintf("        val responses = streamReceive(\"%s\", req.toByteArray())\n", cmd.Snake))
			b.WriteString(fmt.Sprintf("        return responses.map { %s.parseFrom(it) }\n", respCls))
			b.WriteString("    }\n")
		} else {
			b.WriteString(fmt.Sprintf("    open suspend fun %s(messages: List<%s>): %s {\n", methodName, reqCls, respCls))
			b.WriteString("        val raw = messages.map { it.toByteArray() }\n")
			b.WriteString(fmt.Sprintf("        val respData = streamSend(\"%s\", raw, \"%s\")\n", cmd.Snake, cmd.Snake))
			b.WriteString(fmt.Sprintf("        return %s.parseFrom(respData)\n", respCls))
			b.WriteString("    }\n")
		}
	}

	b.WriteString("}\n")

	return b.String()
}
