package main

import (
	"fmt"
	"strings"
)

func generateDartClient(commands []Command, streaming map[string]string, pkg string) string {
	var b strings.Builder

	b.WriteString("/* Auto-generated by generate-handlers — DO NOT EDIT */\n")
	b.WriteString("import 'dart:typed_data';\n")
	b.WriteByte('\n')
	b.WriteString("import 'package:" + pkg + "_central/proto/" + pkg + ".pb.dart';\n")
	b.WriteByte('\n')
	b.WriteString("/// Auto-generated RPC method wrappers.\n")
	b.WriteString("mixin GeneratedClientMixin {\n")
	b.WriteString("  Future<Uint8List> call(String cmdName, Uint8List requestData);\n")
	b.WriteString("  Future<List<Uint8List>> streamReceive(String cmdName, Uint8List requestData);\n")
	b.WriteString("  Future<Uint8List> streamSend(\n")
	b.WriteString("      String cmdName, List<Uint8List> messages, String finalCmdName);\n")

	for _, cmd := range commands {
		if _, ok := streaming[cmd.Snake]; ok {
			continue
		}

		reqCls := cmd.RequestMsg
		respCls := cmd.ResponseMsg
		methodName := toLowerCamel(cmd.Camel)

		// Build parameters
		var params []string
		for _, f := range cmd.RequestFields {
			dtType := resolveDartType(f)
			def := resolveDartDefault(f)
			propName := dartPropertyName(f.Name)
			params = append(params, fmt.Sprintf("%s %s = %s", dtType, propName, def))
		}

		paramsStr := strings.Join(params, ", ")
		if paramsStr != "" {
			paramsStr = "{" + paramsStr + "}"
		}

		b.WriteByte('\n')
		b.WriteString(fmt.Sprintf("  Future<%s> %s(%s) async {\n", respCls, methodName, paramsStr))

		// Build cascade assignment — single field on one line, multiple fields multiline
		if len(cmd.RequestFields) <= 1 {
			if len(cmd.RequestFields) == 1 {
				propName := dartPropertyName(cmd.RequestFields[0].Name)
				b.WriteString(fmt.Sprintf("    final req = %s()..%s = %s;\n", reqCls, propName, propName))
			} else {
				b.WriteString(fmt.Sprintf("    final req = %s();\n", reqCls))
			}
		} else {
			b.WriteString(fmt.Sprintf("    final req = %s()\n", reqCls))
			for i, f := range cmd.RequestFields {
				propName := dartPropertyName(f.Name)
				if i < len(cmd.RequestFields)-1 {
					b.WriteString(fmt.Sprintf("      ..%s = %s\n", propName, propName))
				} else {
					b.WriteString(fmt.Sprintf("      ..%s = %s;\n", propName, propName))
				}
			}
		}

		b.WriteString("    final respData =\n")
		b.WriteString(fmt.Sprintf("        await call('%s', Uint8List.fromList(req.writeToBuffer()));\n", cmd.Snake))
		b.WriteString(fmt.Sprintf("    return %s.fromBuffer(respData);\n", respCls))
		b.WriteString("  }\n")
	}

	// Streaming methods
	for _, cmd := range commands {
		dir, ok := streaming[cmd.Snake]
		if !ok {
			continue
		}

		reqCls := cmd.RequestMsg
		respCls := cmd.ResponseMsg
		methodName := toLowerCamel(cmd.Camel)

		b.WriteByte('\n')

		if dir == "p2c" {
			var params []string
			for _, f := range cmd.RequestFields {
				dtType := resolveDartType(f)
				def := resolveDartDefault(f)
				propName := dartPropertyName(f.Name)
				params = append(params, fmt.Sprintf("%s %s = %s", dtType, propName, def))
			}
			paramsStr := strings.Join(params, ", ")
			if paramsStr != "" {
				paramsStr = "{" + paramsStr + "}"
			}

			b.WriteString(fmt.Sprintf("  Future<List<%s>> %s(%s) async {\n", respCls, methodName, paramsStr))

			if len(cmd.RequestFields) <= 1 {
				if len(cmd.RequestFields) == 1 {
					propName := dartPropertyName(cmd.RequestFields[0].Name)
					b.WriteString(fmt.Sprintf("    final req = %s()..%s = %s;\n", reqCls, propName, propName))
				} else {
					b.WriteString(fmt.Sprintf("    final req = %s();\n", reqCls))
				}
			} else {
				b.WriteString(fmt.Sprintf("    final req = %s()\n", reqCls))
				for i, f := range cmd.RequestFields {
					propName := dartPropertyName(f.Name)
					if i < len(cmd.RequestFields)-1 {
						b.WriteString(fmt.Sprintf("      ..%s = %s\n", propName, propName))
					} else {
						b.WriteString(fmt.Sprintf("      ..%s = %s;\n", propName, propName))
					}
				}
			}

			b.WriteString("    final responses = await streamReceive(\n")
			b.WriteString(fmt.Sprintf("        '%s', Uint8List.fromList(req.writeToBuffer()));\n", cmd.Snake))
			b.WriteString("    return responses\n")
			b.WriteString(fmt.Sprintf("        .map((data) => %s.fromBuffer(data))\n", respCls))
			b.WriteString("        .toList();\n")
			b.WriteString("  }\n")
		} else {
			b.WriteString(fmt.Sprintf("  Future<%s> %s(\n", respCls, methodName))
			b.WriteString(fmt.Sprintf("      List<%s> messages) async {\n", reqCls))
			b.WriteString("    final raw =\n")
			b.WriteString("        messages.map((m) => Uint8List.fromList(m.writeToBuffer())).toList();\n")
			b.WriteString(fmt.Sprintf("    final respData = await streamSend('%s', raw, '%s');\n", cmd.Snake, cmd.Snake))
			b.WriteString(fmt.Sprintf("    return %s.fromBuffer(respData);\n", respCls))
			b.WriteString("  }\n")
		}
	}

	b.WriteString("}\n")

	return b.String()
}
