package main

import (
	"fmt"
	"strings"
)

func generatePyHandlers(commands []Command, pkg string) string {
	var b strings.Builder

	b.WriteString("\"\"\"Auto-generated by generate-handlers — DO NOT EDIT.\"\"\"\n")
	b.WriteByte('\n')
	b.WriteString("import os\n")
	b.WriteString("import sys\n")
	b.WriteByte('\n')
	b.WriteString("sys.path.insert(0, os.path.join(os.path.dirname(__file__), \"..\", \"central_py\"))\n")
	b.WriteString("from " + pkg + ".generated import " + pkg + "_pb2\n")
	b.WriteByte('\n')
	b.WriteByte('\n')

	for _, cmd := range commands {
		reqCls := "" + pkg + "_pb2." + cmd.RequestMsg
		respCls := "" + pkg + "_pb2." + cmd.ResponseMsg
		b.WriteString(fmt.Sprintf("def handle_%s(req_data):\n", cmd.Snake))
		b.WriteString(fmt.Sprintf("    req = %s()\n", reqCls))
		b.WriteString("    req.ParseFromString(req_data)\n")
		b.WriteString(fmt.Sprintf("    return %s().SerializeToString()\n", respCls))
		b.WriteByte('\n')
		b.WriteByte('\n')
	}

	// HANDLERS dict
	b.WriteString("HANDLERS = {\n")
	for _, cmd := range commands {
		b.WriteString(fmt.Sprintf("    \"%s\": handle_%s,\n", cmd.Snake, cmd.Snake))
	}
	b.WriteString("}\n")

	return b.String()
}

func generatePyClient(commands []Command, streaming map[string]string, pkg string) string {
	var b strings.Builder

	b.WriteString("\"\"\"Auto-generated by generate-handlers — DO NOT EDIT.\"\"\"\n")
	b.WriteByte('\n')
	b.WriteString("from __future__ import annotations\n")
	b.WriteByte('\n')
	b.WriteString("from . import " + pkg + "_pb2\n")
	b.WriteByte('\n')
	b.WriteByte('\n')
	b.WriteString("class GeneratedClientMixin:\n")
	b.WriteString("    \"\"\"Auto-generated RPC methods (unary and streaming).\n")
	b.WriteByte('\n')
	b.WriteString("    Requires _call, stream_receive, and stream_send from BlerpcClient.\n")
	b.WriteString("    \"\"\"\n")
	b.WriteByte('\n')

	first := true
	for _, cmd := range commands {
		if _, ok := streaming[cmd.Snake]; ok {
			continue
		}

		reqCls := "" + pkg + "_pb2." + cmd.RequestMsg
		respCls := "" + pkg + "_pb2." + cmd.ResponseMsg

		// Build keyword args
		var params []string
		for _, f := range cmd.RequestFields {
			def := resolvePythonDefault(f)
			params = append(params, fmt.Sprintf("%s=%s", f.Name, def))
		}

		paramsStr := strings.Join(params, ", ")
		if paramsStr != "" {
			paramsStr = ", *, " + paramsStr
		}

		// Build request constructor kwargs
		var kwargs []string
		for _, f := range cmd.RequestFields {
			kwargs = append(kwargs, fmt.Sprintf("%s=%s", f.Name, f.Name))
		}
		kwargsStr := strings.Join(kwargs, ", ")

		if !first {
			b.WriteByte('\n')
		}
		first = false

		b.WriteString(fmt.Sprintf("    async def %s(self%s):\n", cmd.Snake, paramsStr))
		b.WriteString(fmt.Sprintf("        \"\"\"Call the %s command.\"\"\"\n", cmd.Snake))
		b.WriteString(fmt.Sprintf("        req = %s(%s)\n", reqCls, kwargsStr))
		b.WriteString(fmt.Sprintf("        resp_data = await self._call(\"%s\", req.SerializeToString())\n", cmd.Snake))
		b.WriteString(fmt.Sprintf("        resp = %s()\n", respCls))
		b.WriteString("        resp.ParseFromString(resp_data)\n")
		b.WriteString("        return resp\n")
	}

	// Streaming methods
	for _, cmd := range commands {
		dir, ok := streaming[cmd.Snake]
		if !ok {
			continue
		}

		reqCls := "" + pkg + "_pb2." + cmd.RequestMsg
		respCls := "" + pkg + "_pb2." + cmd.ResponseMsg

		b.WriteByte('\n')

		if dir == "p2c" {
			// Build keyword args (same as unary)
			var params []string
			for _, f := range cmd.RequestFields {
				def, ok := pythonDefaults[f.Type]
				if !ok {
					def = "None"
				}
				params = append(params, fmt.Sprintf("%s=%s", f.Name, def))
			}
			paramsStr := strings.Join(params, ", ")
			if paramsStr != "" {
				paramsStr = ", *, " + paramsStr
			}

			var kwargs []string
			for _, f := range cmd.RequestFields {
				kwargs = append(kwargs, fmt.Sprintf("%s=%s", f.Name, f.Name))
			}
			kwargsStr := strings.Join(kwargs, ", ")

			b.WriteString(fmt.Sprintf("    async def %s(self%s):\n", cmd.Snake, paramsStr))
			b.WriteString(fmt.Sprintf("        \"\"\"P2C stream: %s.\"\"\"\n", cmd.Snake))
			b.WriteString(fmt.Sprintf("        req = %s(%s)\n", reqCls, kwargsStr))
			b.WriteString("        results = []\n")
			b.WriteString("        async for data in self.stream_receive(\n")
			b.WriteString(fmt.Sprintf("            \"%s\", req.SerializeToString()\n", cmd.Snake))
			b.WriteString("        ):\n")
			b.WriteString(fmt.Sprintf("            resp = %s()\n", respCls))
			b.WriteString("            resp.ParseFromString(data)\n")
			b.WriteString("            results.append(resp)\n")
			b.WriteString("        return results\n")
		} else {
			// c2p: takes list of typed request messages
			b.WriteString(fmt.Sprintf("    async def %s(self, messages):\n", cmd.Snake))
			b.WriteString(fmt.Sprintf("        \"\"\"C2P stream: %s.\"\"\"\n", cmd.Snake))
			b.WriteString("        raw = [m.SerializeToString() for m in messages]\n")
			b.WriteString(fmt.Sprintf("        resp_data = await self.stream_send(\"%s\", raw, \"%s\")\n", cmd.Snake, cmd.Snake))
			b.WriteString(fmt.Sprintf("        resp = %s()\n", respCls))
			b.WriteString("        resp.ParseFromString(resp_data)\n")
			b.WriteString("        return resp\n")
		}
	}

	return b.String()
}
