package main

import (
	"fmt"
	"strings"
)

func generateTsClient(commands []Command, streaming map[string]string, pkg string) string {
	var b strings.Builder

	b.WriteString("/* Auto-generated by generate-handlers — DO NOT EDIT */\n")
	b.WriteString("import { " + pkg + " } from '../proto/" + pkg + "';\n")
	b.WriteByte('\n')
	b.WriteString("export abstract class GeneratedClient {\n")
	b.WriteString("  protected abstract call(cmdName: string, requestData: Uint8Array): Promise<Uint8Array>;\n")
	b.WriteString("  protected abstract streamReceive(cmdName: string, requestData: Uint8Array): Promise<Uint8Array[]>;\n")
	b.WriteString("  protected abstract streamSend(\n")
	b.WriteString("    cmdName: string,\n")
	b.WriteString("    messages: Uint8Array[],\n")
	b.WriteString("    finalCmdName: string,\n")
	b.WriteString("  ): Promise<Uint8Array>;\n")

	for _, cmd := range commands {
		if _, ok := streaming[cmd.Snake]; ok {
			continue
		}

		reqCls := pkg + "." + cmd.RequestMsg
		respCls := pkg + "." + cmd.ResponseMsg
		methodName := toLowerCamel(cmd.Camel)

		// Build parameters and type annotations
		var params []string
		var typeFields []string
		for _, f := range cmd.RequestFields {
			tsType := resolveTsType(f)
			def := resolveTsDefault(f)
			propName := tsPropertyName(f.Name)
			params = append(params, fmt.Sprintf("%s = %s", propName, def))
			typeFields = append(typeFields, fmt.Sprintf("%s?: %s", propName, tsType))
		}

		b.WriteByte('\n')
		if len(cmd.RequestFields) > 0 {
			// Destructured parameter with defaults
			paramsStr := strings.Join(params, ", ")
			typeStr := strings.Join(typeFields, "; ")
			singleLine := fmt.Sprintf("  async %s({ %s }: { %s } = {}): Promise<%s> {",
				methodName, paramsStr, typeStr, respCls)
			if len(singleLine) <= 100 {
				b.WriteString(singleLine + "\n")
			} else {
				// Multi-line destructured parameters (Prettier-compatible)
				b.WriteString(fmt.Sprintf("  async %s({\n", methodName))
				for _, p := range params {
					b.WriteString(fmt.Sprintf("    %s,\n", p))
				}
				b.WriteString(fmt.Sprintf("  }: { %s } = {}): Promise<%s> {\n", typeStr, respCls))
			}
		} else {
			b.WriteString(fmt.Sprintf("  async %s(): Promise<%s> {\n", methodName, respCls))
		}

		// Create request
		if len(cmd.RequestFields) > 0 {
			var createFields []string
			for _, f := range cmd.RequestFields {
				propName := tsPropertyName(f.Name)
				createFields = append(createFields, propName)
			}
			b.WriteString(fmt.Sprintf("    const req = %s.create({ %s });\n", reqCls, strings.Join(createFields, ", ")))
		} else {
			b.WriteString(fmt.Sprintf("    const req = %s.create({});\n", reqCls))
		}

		b.WriteString(fmt.Sprintf("    const respData = await this.call('%s', %s.encode(req).finish());\n", cmd.Snake, reqCls))
		b.WriteString(fmt.Sprintf("    return %s.decode(respData);\n", respCls))
		b.WriteString("  }\n")
	}

	// Streaming methods
	for _, cmd := range commands {
		dir, ok := streaming[cmd.Snake]
		if !ok {
			continue
		}

		reqCls := pkg + "." + cmd.RequestMsg
		respCls := pkg + "." + cmd.ResponseMsg
		methodName := toLowerCamel(cmd.Camel)

		b.WriteByte('\n')

		if dir == "p2c" {
			var params []string
			var typeFields []string
			for _, f := range cmd.RequestFields {
				tsType := resolveTsType(f)
				def := resolveTsDefault(f)
				propName := tsPropertyName(f.Name)
				params = append(params, fmt.Sprintf("%s = %s", propName, def))
				typeFields = append(typeFields, fmt.Sprintf("%s?: %s", propName, tsType))
			}

			if len(cmd.RequestFields) > 0 {
				paramsStr := strings.Join(params, ", ")
				typeStr := strings.Join(typeFields, "; ")
				singleLine := fmt.Sprintf("  async %s({ %s }: { %s } = {}): Promise<%s[]> {",
					methodName, paramsStr, typeStr, respCls)
				if len(singleLine) <= 80 {
					b.WriteString(singleLine + "\n")
				} else {
					// Prettier-compatible: wrap return type after Promise<
					b.WriteString(fmt.Sprintf("  async %s({ %s }: { %s } = {}): Promise<\n",
						methodName, paramsStr, typeStr))
					b.WriteString(fmt.Sprintf("    %s[]\n", respCls))
					b.WriteString("  > {\n")
				}
			} else {
				b.WriteString(fmt.Sprintf("  async %s(): Promise<%s[]> {\n", methodName, respCls))
			}

			if len(cmd.RequestFields) > 0 {
				var createFields []string
				for _, f := range cmd.RequestFields {
					propName := tsPropertyName(f.Name)
					createFields = append(createFields, propName)
				}
				b.WriteString(fmt.Sprintf("    const req = %s.create({ %s });\n", reqCls, strings.Join(createFields, ", ")))
			} else {
				b.WriteString(fmt.Sprintf("    const req = %s.create({});\n", reqCls))
			}

			b.WriteString("    const responses = await this.streamReceive(\n")
			b.WriteString(fmt.Sprintf("      '%s',\n", cmd.Snake))
			b.WriteString(fmt.Sprintf("      %s.encode(req).finish(),\n", reqCls))
			b.WriteString("    );\n")
			b.WriteString(fmt.Sprintf("    return responses.map((data) => %s.decode(data));\n", respCls))
			b.WriteString("  }\n")
		} else {
			iReqCls := pkg + ".I" + cmd.RequestMsg
			singleLine := fmt.Sprintf("  async %s(messages: %s[]): Promise<%s> {", methodName, iReqCls, respCls)
			if len(singleLine) <= 80 {
				b.WriteString(singleLine + "\n")
			} else {
				// Prettier-compatible: wrap parameter
				b.WriteString(fmt.Sprintf("  async %s(\n", methodName))
				b.WriteString(fmt.Sprintf("    messages: %s[],\n", iReqCls))
				b.WriteString(fmt.Sprintf("  ): Promise<%s> {\n", respCls))
			}
			b.WriteString("    const raw = messages.map((m) =>\n")
			b.WriteString(fmt.Sprintf("      %s.encode(%s.create(m)).finish(),\n", reqCls, reqCls))
			b.WriteString("    );\n")
			b.WriteString(fmt.Sprintf("    const respData = await this.streamSend('%s', raw, '%s');\n", cmd.Snake, cmd.Snake))
			b.WriteString(fmt.Sprintf("    return %s.decode(respData);\n", respCls))
			b.WriteString("  }\n")
		}
	}

	b.WriteString("}\n")

	return b.String()
}
