// Auto-generated by generate-handlers — DO NOT EDIT
package com.blerpc.android.client

import com.google.protobuf.ByteString

/**
 * Auto-generated RPC methods.
 * Subclass and override for custom behavior.
 */
abstract class GeneratedClient {
    abstract suspend fun call(
        cmdName: String,
        requestData: ByteArray,
    ): ByteArray

    abstract suspend fun streamReceive(
        cmdName: String,
        requestData: ByteArray,
    ): List<ByteArray>

    abstract suspend fun streamSend(
        cmdName: String,
        messages: List<ByteArray>,
        finalCmdName: String,
    ): ByteArray

    open suspend fun echo(message: String = ""): blerpc.Blerpc.EchoResponse {
        val req =
            blerpc.Blerpc.EchoRequest.newBuilder()
                .setMessage(message)
                .build()
        val respData = call("echo", req.toByteArray())
        return blerpc.Blerpc.EchoResponse.parseFrom(respData)
    }

    open suspend fun flashRead(
        address: Int = 0,
        length: Int = 0,
    ): blerpc.Blerpc.FlashReadResponse {
        val req =
            blerpc.Blerpc.FlashReadRequest.newBuilder()
                .setAddress(address)
                .setLength(length)
                .build()
        val respData = call("flash_read", req.toByteArray())
        return blerpc.Blerpc.FlashReadResponse.parseFrom(respData)
    }

    open suspend fun dataWrite(
        data: com.google.protobuf.ByteString = com.google.protobuf.ByteString.EMPTY,
    ): blerpc.Blerpc.DataWriteResponse {
        val req =
            blerpc.Blerpc.DataWriteRequest.newBuilder()
                .setData(data)
                .build()
        val respData = call("data_write", req.toByteArray())
        return blerpc.Blerpc.DataWriteResponse.parseFrom(respData)
    }

    open suspend fun counterStream(count: Int = 0): List<blerpc.Blerpc.CounterStreamResponse> {
        val req =
            blerpc.Blerpc.CounterStreamRequest.newBuilder()
                .setCount(count)
                .build()
        val responses = streamReceive("counter_stream", req.toByteArray())
        return responses.map { blerpc.Blerpc.CounterStreamResponse.parseFrom(it) }
    }

    open suspend fun counterUpload(messages: List<blerpc.Blerpc.CounterUploadRequest>): blerpc.Blerpc.CounterUploadResponse {
        val raw = messages.map { it.toByteArray() }
        val respData = streamSend("counter_upload", raw, "counter_upload")
        return blerpc.Blerpc.CounterUploadResponse.parseFrom(respData)
    }
}
