/* Auto-generated by generate-handlers — DO NOT EDIT */
import { blerpc } from '../proto/blerpc';

export abstract class GeneratedClient {
  protected abstract call(cmdName: string, requestData: Uint8Array): Promise<Uint8Array>;
  protected abstract streamReceive(cmdName: string, requestData: Uint8Array): Promise<Uint8Array[]>;
  protected abstract streamSend(
    cmdName: string,
    messages: Uint8Array[],
    finalCmdName: string,
  ): Promise<Uint8Array>;

  async echo({ message = '' }: { message?: string } = {}): Promise<blerpc.EchoResponse> {
    const req = blerpc.EchoRequest.create({ message });
    const respData = await this.call('echo', blerpc.EchoRequest.encode(req).finish());
    return blerpc.EchoResponse.decode(respData);
  }

  async flashRead({
    address = 0,
    length = 0,
  }: { address?: number; length?: number } = {}): Promise<blerpc.FlashReadResponse> {
    const req = blerpc.FlashReadRequest.create({ address, length });
    const respData = await this.call('flash_read', blerpc.FlashReadRequest.encode(req).finish());
    return blerpc.FlashReadResponse.decode(respData);
  }

  async dataWrite({
    data = new Uint8Array(0),
  }: { data?: Uint8Array } = {}): Promise<blerpc.DataWriteResponse> {
    const req = blerpc.DataWriteRequest.create({ data });
    const respData = await this.call('data_write', blerpc.DataWriteRequest.encode(req).finish());
    return blerpc.DataWriteResponse.decode(respData);
  }

  async counterStream({
    count = 0,
  }: { count?: number } = {}): Promise<blerpc.CounterStreamResponse[]> {
    const req = blerpc.CounterStreamRequest.create({ count });
    const responses = await this.streamReceive(
      'counter_stream',
      blerpc.CounterStreamRequest.encode(req).finish(),
    );
    return responses.map((data) => blerpc.CounterStreamResponse.decode(data));
  }

  async counterUpload(messages: blerpc.ICounterUploadRequest[]): Promise<blerpc.CounterUploadResponse> {
    const raw = messages.map((m) =>
      blerpc.CounterUploadRequest.encode(blerpc.CounterUploadRequest.create(m)).finish(),
    );
    const respData = await this.streamSend('counter_upload', raw, 'counter_upload');
    return blerpc.CounterUploadResponse.decode(respData);
  }
}
