/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "blerpc.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(blerpc_EchoRequest, blerpc_EchoRequest, 2)


PB_BIND(blerpc_EchoResponse, blerpc_EchoResponse, 2)


PB_BIND(blerpc_FlashReadRequest, blerpc_FlashReadRequest, AUTO)


PB_BIND(blerpc_FlashReadResponse, blerpc_FlashReadResponse, AUTO)


PB_BIND(blerpc_DataWriteRequest, blerpc_DataWriteRequest, AUTO)


PB_BIND(blerpc_DataWriteResponse, blerpc_DataWriteResponse, AUTO)


PB_BIND(blerpc_CounterStreamRequest, blerpc_CounterStreamRequest, AUTO)


PB_BIND(blerpc_CounterStreamResponse, blerpc_CounterStreamResponse, AUTO)


PB_BIND(blerpc_CounterUploadRequest, blerpc_CounterUploadRequest, AUTO)


PB_BIND(blerpc_CounterUploadResponse, blerpc_CounterUploadResponse, AUTO)



