/* Auto-generated by generate-handlers — DO NOT EDIT */
#ifndef BLERPC_GENERATED_HANDLERS_H
#define BLERPC_GENERATED_HANDLERS_H

#include <stdint.h>
#include <stddef.h>
#include <pb_encode.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef int (*command_handler_fn)(const uint8_t *req_data, size_t req_len,
                                  pb_ostream_t *ostream);

struct handler_entry {
    const char *name;
    uint8_t name_len;
    command_handler_fn handler;
};

command_handler_fn handlers_lookup(const char *name, uint8_t name_len);

int handle_echo(const uint8_t *req_data, size_t req_len,
                    pb_ostream_t *ostream);

int handle_flash_read(const uint8_t *req_data, size_t req_len,
                          pb_ostream_t *ostream);

int handle_data_write(const uint8_t *req_data, size_t req_len,
                          pb_ostream_t *ostream);

#ifdef __cplusplus
}
#endif

#endif /* BLERPC_GENERATED_HANDLERS_H */
