/* Auto-generated by generate-handlers — DO NOT EDIT */
#include "generated_handlers.h"
#include "blerpc.pb.h"
#include <pb_encode.h>
#include <pb_decode.h>
#include <string.h>

/* Discard callback for FT_CALLBACK fields during decode */
static bool discard_bytes_cb(pb_istream_t *stream, const pb_field_t *field,
                             void **arg)
{
    (void)field;
    (void)arg;
    uint8_t buf[64];
    size_t left = stream->bytes_left;
    while (left > 0) {
        size_t n = left < sizeof(buf) ? left : sizeof(buf);
        if (!pb_read(stream, buf, n)) return false;
        left -= n;
    }
    return true;
}

__attribute__((weak))
int handle_echo(const uint8_t *req_data, size_t req_len,
                    pb_ostream_t *ostream)
{
    blerpc_EchoRequest req = blerpc_EchoRequest_init_zero;
    pb_istream_t stream = pb_istream_from_buffer(req_data, req_len);
    if (!pb_decode(&stream, blerpc_EchoRequest_fields, &req)) return -1;

    blerpc_EchoResponse resp = blerpc_EchoResponse_init_zero;
    if (!pb_encode(ostream, blerpc_EchoResponse_fields, &resp)) return -1;
    return 0;
}

__attribute__((weak))
int handle_flash_read(const uint8_t *req_data, size_t req_len,
                          pb_ostream_t *ostream)
{
    blerpc_FlashReadRequest req = blerpc_FlashReadRequest_init_zero;
    pb_istream_t stream = pb_istream_from_buffer(req_data, req_len);
    if (!pb_decode(&stream, blerpc_FlashReadRequest_fields, &req)) return -1;

    blerpc_FlashReadResponse resp = blerpc_FlashReadResponse_init_zero;
    if (!pb_encode(ostream, blerpc_FlashReadResponse_fields, &resp)) return -1;
    return 0;
}

__attribute__((weak))
int handle_data_write(const uint8_t *req_data, size_t req_len,
                          pb_ostream_t *ostream)
{
    blerpc_DataWriteRequest req = blerpc_DataWriteRequest_init_zero;
    req.data.funcs.decode = discard_bytes_cb;
    pb_istream_t stream = pb_istream_from_buffer(req_data, req_len);
    if (!pb_decode(&stream, blerpc_DataWriteRequest_fields, &req)) return -1;

    blerpc_DataWriteResponse resp = blerpc_DataWriteResponse_init_zero;
    if (!pb_encode(ostream, blerpc_DataWriteResponse_fields, &resp)) return -1;
    return 0;
}

static const struct handler_entry handler_table[] = {
    {"echo", 4, handle_echo},
    {"flash_read", 10, handle_flash_read},
    {"data_write", 10, handle_data_write},
};

command_handler_fn handlers_lookup(const char *name, uint8_t name_len)
{
    size_t i;
    for (i = 0; i < sizeof(handler_table) / sizeof(handler_table[0]); i++) {
        if (handler_table[i].name_len == name_len &&
            memcmp(handler_table[i].name, name, name_len) == 0) {
            return handler_table[i].handler;
        }
    }
    return NULL;
}
