/* Auto-generated by generate-handlers — DO NOT EDIT */
#ifndef BLERPC_GENERATED_CLIENT_H
#define BLERPC_GENERATED_CLIENT_H

#include "blerpc.pb.h"
#include <pb_encode.h>
#include <pb_decode.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Callback for P2C streaming response payloads */
typedef int (*blerpc_on_stream_resp_t)(const uint8_t *data, size_t len, void *ctx);

/* Callback for C2P streaming message serialization */
typedef int (*blerpc_next_msg_t)(size_t index, uint8_t *buf, size_t buf_size,
                                 size_t *len, void *ctx);

/* User-provided RPC transport functions */
extern int blerpc_rpc_call(const char *cmd_name,
                           const uint8_t *req_data, size_t req_len,
                           uint8_t *resp_data, size_t resp_size, size_t *resp_len);

extern int blerpc_stream_receive(const char *cmd_name,
                                 const uint8_t *req_data, size_t req_len,
                                 blerpc_on_stream_resp_t on_resp, void *ctx);

extern int blerpc_stream_send(const char *cmd_name, size_t msg_count,
                              blerpc_next_msg_t next_msg, void *msg_ctx,
                              const char *final_cmd_name,
                              uint8_t *resp_data, size_t resp_size, size_t *resp_len);

/* Generated typed RPC functions */
int blerpc_echo(const char *message, blerpc_EchoResponse *resp);
int blerpc_flash_read(uint32_t address, uint32_t length, blerpc_FlashReadResponse *resp, uint8_t *data_buf, size_t data_buf_size, size_t *data_len);
int blerpc_data_write(const uint8_t *data, size_t data_len, uint8_t *work_buf, size_t work_buf_size, blerpc_DataWriteResponse *resp);
int blerpc_counter_stream(uint32_t count, blerpc_CounterStreamResponse *results, size_t max_results, size_t *result_count);
int blerpc_counter_upload(const blerpc_CounterUploadRequest *messages, size_t msg_count, blerpc_CounterUploadResponse *resp);

#ifdef __cplusplus
}
#endif

#endif /* BLERPC_GENERATED_CLIENT_H */
