/* Auto-generated by generate-handlers — DO NOT EDIT */
#include "generated_client.h"

#ifndef BLERPC_GENERATED_RESP_BUF_SIZE
#define BLERPC_GENERATED_RESP_BUF_SIZE 4096
#endif
static uint8_t _blerpc_resp_buf[BLERPC_GENERATED_RESP_BUF_SIZE];

/* Decode context for FT_CALLBACK bytes fields */
struct _blerpc_bytes_decode_ctx {
    uint8_t *buf;
    size_t buf_size;
    size_t decoded_len;
};

static bool _blerpc_decode_bytes_cb(pb_istream_t *stream,
                                     const pb_field_t *field, void **arg)
{
    (void)field;
    struct _blerpc_bytes_decode_ctx *ctx =
        (struct _blerpc_bytes_decode_ctx *)*arg;
    size_t len = stream->bytes_left;
    if (len > ctx->buf_size - ctx->decoded_len) return false;
    if (!pb_read(stream, ctx->buf + ctx->decoded_len, len)) return false;
    ctx->decoded_len += len;
    return true;
}

/* Encode context for FT_CALLBACK bytes fields */
struct _blerpc_bytes_encode_ctx {
    const uint8_t *data;
    size_t data_len;
};

static bool _blerpc_encode_bytes_cb(pb_ostream_t *stream,
                                     const pb_field_t *field,
                                     void *const *arg)
{
    const struct _blerpc_bytes_encode_ctx *ctx =
        *(const struct _blerpc_bytes_encode_ctx **)arg;
    if (!pb_encode_tag_for_field(stream, field)) return false;
    if (!pb_encode_varint(stream, ctx->data_len)) return false;
    return pb_write(stream, ctx->data, ctx->data_len);
}

int blerpc_echo(const char *message, blerpc_EchoResponse *resp)
{
    blerpc_EchoRequest req = blerpc_EchoRequest_init_zero;
    strncpy(req.message, message, sizeof(req.message) - 1);

    uint8_t req_buf[blerpc_EchoRequest_size];
    pb_ostream_t ostream = pb_ostream_from_buffer(req_buf, sizeof(req_buf));
    if (!pb_encode(&ostream, blerpc_EchoRequest_fields, &req)) return -1;

    uint8_t resp_buf[blerpc_EchoResponse_size];
    size_t resp_len;
    if (blerpc_rpc_call("echo", req_buf, ostream.bytes_written,
                        resp_buf, sizeof(resp_buf), &resp_len) != 0) return -1;

    *resp = (blerpc_EchoResponse)blerpc_EchoResponse_init_zero;
    pb_istream_t istream = pb_istream_from_buffer(resp_buf, resp_len);
    if (!pb_decode(&istream, blerpc_EchoResponse_fields, resp)) return -1;

    return 0;
}

int blerpc_flash_read(uint32_t address, uint32_t length, blerpc_FlashReadResponse *resp, uint8_t *data_buf, size_t data_buf_size, size_t *data_len)
{
    blerpc_FlashReadRequest req = blerpc_FlashReadRequest_init_zero;
    req.address = address;
    req.length = length;

    uint8_t req_buf[blerpc_FlashReadRequest_size];
    pb_ostream_t ostream = pb_ostream_from_buffer(req_buf, sizeof(req_buf));
    if (!pb_encode(&ostream, blerpc_FlashReadRequest_fields, &req)) return -1;

    size_t resp_len;
    if (blerpc_rpc_call("flash_read", req_buf, ostream.bytes_written,
                        _blerpc_resp_buf, sizeof(_blerpc_resp_buf),
                        &resp_len) != 0) return -1;

    struct _blerpc_bytes_decode_ctx _data_ctx = {
        .buf = data_buf, .buf_size = data_buf_size, .decoded_len = 0
    };
    *resp = (blerpc_FlashReadResponse)blerpc_FlashReadResponse_init_zero;
    resp->data.funcs.decode = _blerpc_decode_bytes_cb;
    resp->data.arg = &_data_ctx;
    pb_istream_t istream = pb_istream_from_buffer(_blerpc_resp_buf, resp_len);
    if (!pb_decode(&istream, blerpc_FlashReadResponse_fields, resp)) return -1;

    *data_len = _data_ctx.decoded_len;

    return 0;
}

int blerpc_data_write(const uint8_t *data, size_t data_len, uint8_t *work_buf, size_t work_buf_size, blerpc_DataWriteResponse *resp)
{
    struct _blerpc_bytes_encode_ctx _data_ctx = {
        .data = data, .data_len = data_len
    };
    blerpc_DataWriteRequest req = blerpc_DataWriteRequest_init_zero;
    req.data.funcs.encode = _blerpc_encode_bytes_cb;
    req.data.arg = &_data_ctx;

    pb_ostream_t sizing = PB_OSTREAM_SIZING;
    if (!pb_encode(&sizing, blerpc_DataWriteRequest_fields, &req)) return -1;
    if (sizing.bytes_written > work_buf_size) return -1;

    pb_ostream_t ostream = pb_ostream_from_buffer(work_buf, work_buf_size);
    if (!pb_encode(&ostream, blerpc_DataWriteRequest_fields, &req)) return -1;

    uint8_t resp_buf[blerpc_DataWriteResponse_size];
    size_t resp_len;
    if (blerpc_rpc_call("data_write", work_buf, ostream.bytes_written,
                        resp_buf, sizeof(resp_buf), &resp_len) != 0) return -1;

    *resp = (blerpc_DataWriteResponse)blerpc_DataWriteResponse_init_zero;
    pb_istream_t istream = pb_istream_from_buffer(resp_buf, resp_len);
    if (!pb_decode(&istream, blerpc_DataWriteResponse_fields, resp)) return -1;

    return 0;
}

struct _blerpc_counter_stream_ctx {
    blerpc_CounterStreamResponse *results;
    size_t max_results;
    size_t count;
};

static int _blerpc_counter_stream_on_resp(const uint8_t *data, size_t len,
                                            void *ctx)
{
    struct _blerpc_counter_stream_ctx *c = (struct _blerpc_counter_stream_ctx *)ctx;
    if (c->count >= c->max_results) return -1;
    c->results[c->count] = (blerpc_CounterStreamResponse)blerpc_CounterStreamResponse_init_zero;
    pb_istream_t istream = pb_istream_from_buffer(data, len);
    if (!pb_decode(&istream, blerpc_CounterStreamResponse_fields, &c->results[c->count])) return -1;
    c->count++;
    return 0;
}

int blerpc_counter_stream(uint32_t count, blerpc_CounterStreamResponse *results, size_t max_results, size_t *result_count)
{
    blerpc_CounterStreamRequest req = blerpc_CounterStreamRequest_init_zero;
    req.count = count;

    uint8_t req_buf[blerpc_CounterStreamRequest_size];
    pb_ostream_t ostream = pb_ostream_from_buffer(req_buf, sizeof(req_buf));
    if (!pb_encode(&ostream, blerpc_CounterStreamRequest_fields, &req)) return -1;

    struct _blerpc_counter_stream_ctx ctx = {
        .results = results, .max_results = max_results, .count = 0
    };
    if (blerpc_stream_receive("counter_stream", req_buf, ostream.bytes_written,
                              _blerpc_counter_stream_on_resp, &ctx) != 0) return -1;

    *result_count = ctx.count;
    return 0;
}

struct _blerpc_counter_upload_ctx {
    const blerpc_CounterUploadRequest *messages;
};

static int _blerpc_counter_upload_next(size_t index, uint8_t *buf,
                                         size_t buf_size, size_t *len, void *ctx)
{
    struct _blerpc_counter_upload_ctx *c = (struct _blerpc_counter_upload_ctx *)ctx;
    pb_ostream_t ostream = pb_ostream_from_buffer(buf, buf_size);
    if (!pb_encode(&ostream, blerpc_CounterUploadRequest_fields, &c->messages[index])) return -1;
    *len = ostream.bytes_written;
    return 0;
}

int blerpc_counter_upload(const blerpc_CounterUploadRequest *messages, size_t msg_count, blerpc_CounterUploadResponse *resp)
{
    struct _blerpc_counter_upload_ctx ctx = { .messages = messages };

    uint8_t resp_buf[blerpc_CounterUploadResponse_size];
    size_t resp_len;
    if (blerpc_stream_send("counter_upload", msg_count,
                           _blerpc_counter_upload_next, &ctx,
                           "counter_upload", resp_buf, sizeof(resp_buf),
                           &resp_len) != 0) return -1;

    *resp = (blerpc_CounterUploadResponse)blerpc_CounterUploadResponse_init_zero;
    pb_istream_t istream = pb_istream_from_buffer(resp_buf, resp_len);
    if (!pb_decode(&istream, blerpc_CounterUploadResponse_fields, resp)) return -1;

    return 0;
}

